const json = (data, status=200, headers={}) => new Response(JSON.stringify(data), {status, headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff',...headers}});
const bad = (message, status=400) => json({error:message}, status);
const text = (value) => value == null ? '' : String(value);
const now = () => new Date().toISOString();
const slugify = (s) => text(s).toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'') || ('product-'+Date.now());
const enc = new TextEncoder();
async function sha256(value){const b=await crypto.subtle.digest('SHA-256',enc.encode(value));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('');}
async function hmac(secret, value){const key=await crypto.subtle.importKey('raw',enc.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const sig=await crypto.subtle.sign('HMAC',key,enc.encode(value));return [...new Uint8Array(sig)].map(x=>x.toString(16).padStart(2,'0')).join('');}
function timingSafe(a,b){if(typeof a!=='string'||typeof b!=='string'||a.length!==b.length)return false;let r=0;for(let i=0;i<a.length;i++)r|=a.charCodeAt(i)^b.charCodeAt(i);return r===0;}
function cookieOpts(url, maxAge=2592000){return `Path=/; HttpOnly; SameSite=Strict; Max-Age=${maxAge}${url.protocol==='https:'?'; Secure':''}`;}
function cookie(name,value,opts=''){return `${name}=${encodeURIComponent(value)}; ${opts}`;}
function readCookie(request,name){const c=request.headers.get('Cookie')||'';for(const part of c.split(';')){const [k,...v]=part.trim().split('=');if(k===name)return decodeURIComponent(v.join('='));}return null;}
async function adminSession(request,env){const token=readCookie(request,'lh_session');if(!token)return null;const hash=await sha256(token);const row=await env.DB.prepare('SELECT * FROM sessions WHERE token_hash=? AND expires_at>?').bind(hash,now()).first();return row||null;}
async function requireAdmin(request,env){const session=await adminSession(request,env);if(!session)return {response:bad('Unauthorized',401)};const csrf=request.headers.get('X-CSRF-Token');if(['POST','PUT','PATCH','DELETE'].includes(request.method)&&csrf!==session.csrf_token)return {response:bad('Invalid CSRF token',403)};return {session};}
async function bodyJSON(request){try{return await request.json()}catch{return null}}
async function getSettings(env){const rows=await env.DB.prepare('SELECT key,value FROM settings').all();return Object.fromEntries((rows.results||[]).map(r=>[r.key,r.value]));}
function imageUrl(key){return key ? `/media/${encodeURIComponent(key).replace(/%2F/g,'/')}` : ''}
function productOut(r){let specs={};try{specs=JSON.parse(r.specifications||'{}')}catch{};return {...r,id:Number(r.id),price:Number(r.price),mrp:Number(r.mrp),stock:Number(r.stock),rating:Number(r.rating||0),active:Boolean(r.active),specifications:specs,image_url:imageUrl(r.image_key)};}
async function listProducts(env,url,includeInactive=false){let q='SELECT * FROM products';const where=[];const binds=[];const search=url.searchParams.get('q');const category=url.searchParams.get('category');if(!includeInactive)where.push('active=1');if(search){where.push('(name LIKE ? OR slug LIKE ? OR category LIKE ?)');const s=`%${search}%`;binds.push(s,s,s);}if(category){where.push('category=?');binds.push(category);}if(where.length)q+=' WHERE '+where.join(' AND ');q+=' ORDER BY created_at DESC';const {results=[]}=await env.DB.prepare(q).bind(...binds).all();return results.map(productOut)}
async function createOrder(env,data,paymentMethod){if(!data||!Array.isArray(data.items)||!data.items.length)return bad('Cart is empty');const customer=data.customer||{};for(const k of ['name','phone','address','city','state','pincode'])if(!text(customer[k]).trim())return bad(`Missing ${k}`);if(!/^\d{10}$/.test(text(customer.phone).replace(/\D/g,'')))return bad('Invalid mobile number');if(!/^\d{6}$/.test(text(customer.pincode)))return bad('Invalid pincode');
  const ids=data.items.map(x=>Number(x.productId)).filter(Boolean);if(ids.length!==data.items.length)return bad('Invalid product');
  const placeholders=ids.map(()=>'?').join(',');const {results:products=[]}=await env.DB.prepare(`SELECT * FROM products WHERE id IN (${placeholders}) AND active=1`).bind(...ids).all();const map=new Map(products.map(p=>[Number(p.id),p]));
  let subtotal=0;const items=[];for(const raw of data.items){const p=map.get(Number(raw.productId));const qty=Math.floor(Number(raw.qty));if(!p||!qty||qty<1)return bad('Invalid cart item');if(Number(p.stock)<qty)return bad(`Insufficient stock for ${p.name}`);subtotal+=Number(p.price)*qty;items.push({p,qty});}
  let discount=0;let coupon=null;const code=text(data.couponCode).trim().toUpperCase();if(code){coupon=await env.DB.prepare('SELECT * FROM coupons WHERE code=? AND enabled=1').bind(code).first();if(!coupon)return bad('Coupon not found');if(coupon.expires_at&&new Date(coupon.expires_at)<=new Date())return bad('Coupon expired');if(subtotal<Number(coupon.min_cart))return bad(`Minimum cart value is ₹${coupon.min_cart}`);if(coupon.usage_limit!=null&&Number(coupon.used_count)>=Number(coupon.usage_limit))return bad('Coupon usage limit reached');discount=coupon.type==='percent'?Math.min(subtotal*Number(coupon.value)/100,Number(coupon.max_discount||0)||Number.MAX_SAFE_INTEGER):Math.min(Number(coupon.value),Number(coupon.max_discount||0)||Number(coupon.value));}
  const settings=await getSettings(env);const shipping=subtotal>=Number(settings.free_shipping||499)?0:Number(settings.shipping_fee||49);const total=Math.max(0,Math.round(subtotal-discount+shipping));
  const orderId=`LH-${crypto.randomUUID().split('-')[0].toUpperCase()}`;const idem=text(data.idempotencyKey)||crypto.randomUUID();
  const existing=await env.DB.prepare('SELECT * FROM orders WHERE idempotency_key=?').bind(idem).first();if(existing)return {order:existing};
  const changed=[];try{
    for(const {p,qty} of items){const r=await env.DB.prepare('UPDATE products SET stock=stock-?,updated_at=? WHERE id=? AND stock>=?').bind(qty,now(),p.id,qty).run();if(!(r.meta?.changes||0)){throw new Error(`Insufficient stock for ${p.name}`)}changed.push({id:p.id,qty});}
    if(coupon){const r=await env.DB.prepare('UPDATE coupons SET used_count=used_count+1,updated_at=? WHERE code=? AND enabled=1 AND (usage_limit IS NULL OR used_count<usage_limit)').bind(now(),coupon.code).run();if(!(r.meta?.changes||0))throw new Error('Coupon no longer available');}
    await env.DB.prepare(`INSERT INTO orders(id,idempotency_key,customer_name,phone,email,address,area,landmark,city,state,pincode,subtotal,discount,shipping,total,coupon_code,payment_method,payment_status,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(orderId,idem,text(customer.name),text(customer.phone),text(customer.email),text(customer.address),text(customer.area),text(customer.landmark),text(customer.city),text(customer.state),text(customer.pincode),subtotal,Math.round(discount),shipping,total,coupon?.code||null,paymentMethod,paymentMethod==='cod'?'pending':'pending',paymentMethod==='cod'?'Confirmed':'Pending',now(),now()).run();
    for(const {p,qty} of items)await env.DB.prepare('INSERT INTO order_items(order_id,product_id,name_snapshot,price_snapshot,qty,image_key) VALUES(?,?,?,?,?,?)').bind(orderId,p.id,p.name,p.price,qty,p.image_key||null).run();
    return {order:{id:orderId,status:paymentMethod==='cod'?'Confirmed':'Pending',payment_method:paymentMethod,total,subtotal,discount,shipping},created:true};
  }catch(e){for(const x of changed)await env.DB.prepare('UPDATE products SET stock=stock+?,updated_at=? WHERE id=?').bind(x.qty,now(),x.id).run();if(coupon)await env.DB.prepare('UPDATE coupons SET used_count=CASE WHEN used_count>0 THEN used_count-1 ELSE 0 END,updated_at=? WHERE code=?').bind(now(),coupon.code).run();return bad(e.message||'Could not create order',409)}
}
async function restoreInventory(env,orderId){const order=await env.DB.prepare('SELECT inventory_released FROM orders WHERE id=?').bind(orderId).first();if(!order||Number(order.inventory_released))return;const {results=[]}=await env.DB.prepare('SELECT product_id,qty FROM order_items WHERE order_id=?').bind(orderId).all();for(const i of results)await env.DB.prepare('UPDATE products SET stock=stock+?,updated_at=? WHERE id=?').bind(i.qty,now(),i.product_id).run();await env.DB.prepare('UPDATE orders SET inventory_released=1,updated_at=? WHERE id=?').bind(now(),orderId).run();}
async function razorpayOrder(env,orderId,amount){if(!env.RAZORPAY_KEY_ID||!env.RAZORPAY_KEY_SECRET)return null;const auth=btoa(`${env.RAZORPAY_KEY_ID}:${env.RAZORPAY_KEY_SECRET}`);const res=await fetch('https://api.razorpay.com/v1/orders',{method:'POST',headers:{Authorization:`Basic ${auth}`,'content-type':'application/json'},body:JSON.stringify({amount:Math.round(amount*100),currency:'INR',receipt:orderId,notes:{internal_order_id:orderId}})});if(!res.ok)throw new Error('Razorpay order creation failed');return res.json();}
async function withHeaders(response){const h=new Headers(response.headers);h.set('x-content-type-options','nosniff');h.set('referrer-policy','strict-origin-when-cross-origin');h.set('x-frame-options','SAMEORIGIN');h.set('permissions-policy','camera=(),microphone=(),geolocation=()');h.set('content-security-policy',"default-src 'self'; img-src 'self' data: blob:; style-src 'self' 'unsafe-inline'; script-src 'self' https://checkout.razorpay.com; connect-src 'self' https://api.razorpay.com; frame-src 'self' https://api.razorpay.com https://checkout.razorpay.com; object-src 'none'; base-uri 'self'; form-action 'self';");return new Response(response.body,{status:response.status,headers:h});}
export default {async fetch(request,env){const url=new URL(request.url);try{
  if(url.pathname.startsWith('/api/')){
    if(request.method==='GET'&&url.pathname==='/api/config'){const s=await getSettings(env);return json({storeName:s.store_name||'LUXURIOUS HUB',tagline:s.tagline||'THE EVERYDAY EDIT',whatsapp:s.whatsapp||'',codEnabled:s.cod_enabled!=='0',onlinePaymentEnabled:Boolean(env.RAZORPAY_KEY_ID&&env.RAZORPAY_KEY_SECRET)})}
    if(request.method==='GET'&&url.pathname==='/api/products')return json({products:await listProducts(env,url,false)});
    if(request.method==='GET'&&url.pathname.startsWith('/api/products/')){const slug=decodeURIComponent(url.pathname.split('/').pop());const p=await env.DB.prepare('SELECT * FROM products WHERE slug=? AND active=1').bind(slug).first();if(!p)return bad('Product not found',404);return json({product:productOut(p)});}
    if(request.method==='POST'&&url.pathname==='/api/coupons/validate'){const d=await bodyJSON(request);const c=await env.DB.prepare('SELECT * FROM coupons WHERE code=? AND enabled=1').bind(text(d?.code).trim().toUpperCase()).first();if(!c)return bad('Coupon not found',404);const subtotal=Number(d?.subtotal||0);if(c.expires_at&&new Date(c.expires_at)<=new Date())return bad('Coupon expired');if(subtotal<Number(c.min_cart))return bad(`Minimum cart value is ₹${c.min_cart}`);if(c.usage_limit!=null&&Number(c.used_count)>=Number(c.usage_limit))return bad('Coupon usage limit reached');const discount=c.type==='percent'?Math.min(subtotal*Number(c.value)/100,Number(c.max_discount||0)||Number.MAX_SAFE_INTEGER):Math.min(Number(c.value),Number(c.max_discount||0)||Number(c.value));return json({code:c.code,type:c.type,value:Number(c.value),discount:Math.round(discount)});}
    if(request.method==='POST'&&url.pathname==='/api/orders'){return await createOrder(env,await bodyJSON(request),'cod');}
    if(request.method==='GET'&&url.pathname.startsWith('/api/orders/')){const id=decodeURIComponent(url.pathname.split('/').pop());const phone=url.searchParams.get('phone')||'';const o=await env.DB.prepare('SELECT id,status,payment_method,payment_status,total,created_at,tracking_number,customer_name,phone FROM orders WHERE id=?').bind(id).first();if(!o)return bad('Order not found',404);if(phone&&o.phone!==phone)return bad('Order not found',404);if(!phone)return bad('Mobile number required',401);const {results:items=[]}=await env.DB.prepare('SELECT name_snapshot,qty,price_snapshot FROM order_items WHERE order_id=?').bind(id).all();return json({order:{...o,total:Number(o.total),items}});}
    if(request.method==='POST'&&url.pathname==='/api/payment/create'){if(!env.RAZORPAY_KEY_ID||!env.RAZORPAY_KEY_SECRET)return bad('Online payment is not configured',503);const result=await createOrder(env,await bodyJSON(request),'razorpay');if(result.response)return result.response;let rzp;try{rzp=await razorpayOrder(env,result.order.id,result.order.total)}catch(e){await env.DB.prepare('UPDATE orders SET status=?,payment_status=?,updated_at=? WHERE id=?').bind('Cancelled','failed',now(),result.order.id).run();await restoreInventory(env,result.order.id);return bad(e.message||'Payment order creation failed',502)}await env.DB.prepare('UPDATE orders SET razorpay_order_id=?,updated_at=? WHERE id=?').bind(rzp.id,now(),result.order.id).run();return json({keyId:env.RAZORPAY_KEY_ID,orderId:result.order.id,razorpayOrderId:rzp.id,amount:result.order.total,currency:'INR'});}
    if(request.method==='POST'&&url.pathname==='/api/payment/verify'){if(!env.RAZORPAY_KEY_SECRET)return bad('Payment verification unavailable',503);const d=await bodyJSON(request);const o=await env.DB.prepare('SELECT * FROM orders WHERE id=?').bind(d?.orderId).first();if(!o||o.razorpay_order_id!==d?.razorpay_order_id)return bad('Invalid payment order',400);const expected=await hmac(env.RAZORPAY_KEY_SECRET,`${d.razorpay_order_id}|${d.razorpay_payment_id}`);if(!timingSafe(expected,text(d.razorpay_signature)))return bad('Invalid payment signature',400);await env.DB.prepare('UPDATE orders SET razorpay_payment_id=?,payment_status=?,status=?,updated_at=? WHERE id=?').bind(text(d.razorpay_payment_id),'captured','Confirmed',now(),o.id).run();return json({ok:true,orderId:o.id});}
    if(request.method==='POST'&&url.pathname==='/api/webhooks/razorpay'){const raw=await request.text();if(!env.RAZORPAY_WEBHOOK_SECRET)return bad('Webhook secret not configured',503);const sig=request.headers.get('x-razorpay-signature')||request.headers.get('X-Razorpay-Signature')||'';const expected=await hmac(env.RAZORPAY_WEBHOOK_SECRET,raw);if(!timingSafe(expected,sig))return bad('Invalid webhook signature',400);const eventId=request.headers.get('x-razorpay-event-id')||await sha256(raw+text(request.headers.get('x-razorpay-signature')));try{await env.DB.prepare('INSERT INTO webhook_events(event_id,event_type) VALUES(?,?)').bind(eventId,'razorpay').run()}catch{return json({ok:true})}const data=JSON.parse(raw);const payment=data?.payload?.payment?.entity;const rzpOrder=payment?.order_id;const order=rzpOrder?await env.DB.prepare('SELECT * FROM orders WHERE razorpay_order_id=?').bind(rzpOrder).first():null;if(order){if(data.event==='payment.captured'||data.event==='order.paid'){await env.DB.prepare('UPDATE orders SET payment_status=?,status=?,razorpay_payment_id=COALESCE(?,razorpay_payment_id),updated_at=? WHERE id=?').bind('captured','Confirmed',payment?.id||null,now(),order.id).run()}else if(data.event==='payment.failed'){await env.DB.prepare('UPDATE orders SET payment_status=?,updated_at=? WHERE id=?').bind('failed',now(),order.id).run();await restoreInventory(env,order.id);}}return json({ok:true});}
    if(request.method==='POST'&&url.pathname==='/api/admin/login'){const d=await bodyJSON(request);if(!env.ADMIN_USERNAME||!env.ADMIN_PASSWORD)return bad('Admin credentials are not configured',503);const u=text(d?.username),p=text(d?.password);if(!timingSafe(await sha256(u),await sha256(env.ADMIN_USERNAME))||!timingSafe(await sha256(p),await sha256(env.ADMIN_PASSWORD)))return bad('Invalid credentials',401);const token=crypto.randomUUID()+crypto.randomUUID();const csrf=crypto.randomUUID();await env.DB.prepare('INSERT INTO sessions(token_hash,csrf_token,username,expires_at) VALUES(?,?,?,?)').bind(await sha256(token),csrf,u,new Date(Date.now()+30*864e5).toISOString()).run();return json({ok:true,csrf},200,{'Set-Cookie':cookie('lh_session',token,cookieOpts(url))});}
    if(request.method==='GET'&&url.pathname==='/api/admin/session'){const s=await adminSession(request,env);return json({authenticated:Boolean(s),csrf:s?.csrf_token||null,username:s?.username||null});}
    if(request.method==='POST'&&url.pathname==='/api/admin/logout'){const token=readCookie(request,'lh_session');if(token)await env.DB.prepare('DELETE FROM sessions WHERE token_hash=?').bind(await sha256(token)).run();return json({ok:true},{headers:{'Set-Cookie':cookie('lh_session','',cookieOpts(url,0))}});}
    const auth=await requireAdmin(request,env);if(auth.response)return auth.response;
    if(request.method==='GET'&&url.pathname==='/api/admin/dashboard'){const [p,o,r]=await Promise.all([env.DB.prepare('SELECT COUNT(*) c FROM products WHERE active=1').first(),env.DB.prepare('SELECT COUNT(*) c FROM orders').first(),env.DB.prepare("SELECT COALESCE(SUM(total),0) r FROM orders WHERE payment_status='captured' OR payment_method='cod'").first()]);return json({products:Number(p?.c||0),orders:Number(o?.c||0),revenue:Number(r?.r||0),csrf:auth.session.csrf_token});}
    if(request.method==='GET'&&url.pathname==='/api/admin/orders'){const {results=[]}=await env.DB.prepare('SELECT * FROM orders ORDER BY created_at DESC LIMIT 500').all();return json({orders:results.map(o=>({...o,total:Number(o.total),subtotal:Number(o.subtotal),discount:Number(o.discount),shipping:Number(o.shipping)})),csrf:auth.session.csrf_token});}
    if(request.method==='PATCH'&&url.pathname.startsWith('/api/admin/orders/')){const id=decodeURIComponent(url.pathname.split('/').pop());const d=await bodyJSON(request);const status=text(d?.status);if(!['Pending','Confirmed','Processing','Packed','Shipped','Out for Delivery','Delivered','Cancelled','Returned'].includes(status))return bad('Invalid status');const old=await env.DB.prepare('SELECT * FROM orders WHERE id=?').bind(id).first();if(!old)return bad('Order not found',404);await env.DB.prepare('UPDATE orders SET status=?,tracking_number=COALESCE(?,tracking_number),updated_at=? WHERE id=?').bind(status,text(d?.trackingNumber)||null,now(),id).run();if((status==='Cancelled'||status==='Returned')&&old.inventory_released===0)await restoreInventory(env,id);return json({ok:true});}
    if(request.method==='GET'&&url.pathname==='/api/admin/products')return json({products:await listProducts(env,url,true),csrf:auth.session.csrf_token});
    if(request.method==='POST'&&url.pathname==='/api/admin/products'){const d=await bodyJSON(request);const slug=slugify(d?.slug||d?.name);const r=await env.DB.prepare('INSERT INTO products(slug,name,category,price,mrp,stock,tag,rating,description,specifications,active,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(slug,text(d?.name),text(d?.category),Number(d?.price||0),Number(d?.mrp||0),Number(d?.stock||0),text(d?.tag||'New'),Number(d?.rating||0),text(d?.description||''),JSON.stringify(d?.specifications||{}),d?.active===false?0:1,now(),now()).run();return json({id:r.meta?.last_row_id,slug});}
    if(request.method==='PUT'&&url.pathname.startsWith('/api/admin/products/')){const id=Number(url.pathname.split('/').pop());const d=await bodyJSON(request);const p=await env.DB.prepare('SELECT * FROM products WHERE id=?').bind(id).first();if(!p)return bad('Product not found',404);const slug=slugify(d?.slug||d?.name||p.name);await env.DB.prepare('UPDATE products SET slug=?,name=?,category=?,price=?,mrp=?,stock=?,tag=?,rating=?,description=?,specifications=?,active=?,updated_at=? WHERE id=?').bind(slug,text(d?.name??p.name),text(d?.category??p.category),Number(d?.price??p.price),Number(d?.mrp??p.mrp),Number(d?.stock??p.stock),text(d?.tag??p.tag),Number(d?.rating??p.rating),text(d?.description??p.description),JSON.stringify(d?.specifications??JSON.parse(p.specifications||'{}')),d?.active===false?0:1,now(),id).run();return json({ok:true});}
    if(request.method==='POST'&&/^\/api\/admin\/products\/\d+\/image$/.test(url.pathname)){const id=Number(url.pathname.split('/')[4]);const product=await env.DB.prepare('SELECT * FROM products WHERE id=?').bind(id).first();if(!product)return bad('Product not found',404);const form=await request.formData();const file=form.get('file');if(!(file instanceof File))return bad('Image file required');if(file.size>6*1024*1024)return bad('Image must be 6 MB or smaller');const ext=(file.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'');const key=`products/${id}/${crypto.randomUUID()}.${ext}`;await env.IMAGES.put(key,await file.arrayBuffer(),{httpMetadata:{contentType:file.type||'image/jpeg',cacheControl:'public, max-age=31536000, immutable'}});await env.DB.prepare('INSERT INTO product_images(product_id,object_key,alt_text,sort_order) VALUES(?,?,?,?)').bind(id,key,text(product.name),0).run();await env.DB.prepare('UPDATE products SET image_key=?,updated_at=? WHERE id=?').bind(key,now(),id).run();return json({ok:true,image_url:imageUrl(key),key});}
    if(request.method==='DELETE'&&/^\/api\/admin\/products\/\d+\/image$/.test(url.pathname)){const id=Number(url.pathname.split('/')[4]);const d=await bodyJSON(request);const key=text(d?.key);if(key){await env.IMAGES.delete(key);await env.DB.prepare('DELETE FROM product_images WHERE product_id=? AND object_key=?').bind(id,key).run();}const next=await env.DB.prepare('SELECT object_key FROM product_images WHERE product_id=? ORDER BY sort_order,id LIMIT 1').bind(id).first();await env.DB.prepare('UPDATE products SET image_key=?,updated_at=? WHERE id=?').bind(next?.object_key||null,now(),id).run();return json({ok:true});}
    if(request.method==='GET'&&url.pathname==='/api/admin/coupons'){const {results=[]}=await env.DB.prepare('SELECT * FROM coupons ORDER BY created_at DESC').all();return json({coupons:results,csrf:auth.session.csrf_token});}
    if(request.method==='POST'&&url.pathname==='/api/admin/coupons'){const d=await bodyJSON(request);const code=text(d?.code).trim().toUpperCase();if(!code)return bad('Code required');await env.DB.prepare('INSERT INTO coupons(code,type,value,min_cart,max_discount,enabled,expires_at,usage_limit,used_count,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,0,?,?)').bind(code,d?.type==='fixed'?'fixed':'percent',Number(d?.value||0),Number(d?.minCart||0),Number(d?.maxDiscount||0),d?.enabled===false?0:1,text(d?.expiresAt)||null,d?.usageLimit==null?null:Number(d.usageLimit),now(),now()).run();return json({ok:true});}
    if(request.method==='PATCH'&&url.pathname.startsWith('/api/admin/coupons/')){const code=decodeURIComponent(url.pathname.split('/').pop()).toUpperCase();const d=await bodyJSON(request);await env.DB.prepare('UPDATE coupons SET enabled=?,value=?,min_cart=?,max_discount=?,expires_at=?,usage_limit=?,updated_at=? WHERE code=?').bind(d?.enabled===false?0:1,Number(d?.value||0),Number(d?.minCart||0),Number(d?.maxDiscount||0),text(d?.expiresAt)||null,d?.usageLimit==null?null:Number(d.usageLimit),now(),code).run();return json({ok:true});}
    if(request.method==='GET'&&url.pathname==='/api/admin/settings'){return json({settings:await getSettings(env),csrf:auth.session.csrf_token});}
    if(request.method==='PUT'&&url.pathname==='/api/admin/settings'){const d=await bodyJSON(request);for(const [key,value] of Object.entries(d||{}))await env.DB.prepare('INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value').bind(key,text(value)).run();return json({ok:true});}
    if(request.method==='GET'&&url.pathname==='/api/admin/customers'){const {results=[]}=await env.DB.prepare('SELECT customer_name,phone,email,COUNT(*) orders,COALESCE(SUM(total),0) spent,MAX(created_at) last_order FROM orders GROUP BY phone,email,customer_name ORDER BY last_order DESC LIMIT 500').all();return json({customers:results.map(x=>({...x,orders:Number(x.orders),spent:Number(x.spent)})),csrf:auth.session.csrf_token});}
    return bad('Not found',404);
  }
  if(url.pathname==='/media/'||url.pathname.startsWith('/media/')){const key=decodeURIComponent(url.pathname.slice('/media/'.length));if(!key)return bad('Not found',404);const obj=await env.IMAGES.get(key);if(!obj)return bad('Image not found',404);const headers=new Headers();obj.writeHttpMetadata(headers);headers.set('cache-control','public, max-age=31536000, immutable');headers.set('etag',obj.httpEtag);headers.set('x-content-type-options','nosniff');return new Response(obj.body,{headers});}
  if(url.pathname==='/'||url.pathname.startsWith('/index.html')||url.pathname.startsWith('/admin.html'))return withHeaders(await env.ASSETS.fetch(request));
  return withHeaders(await env.ASSETS.fetch(request));
 }catch(e){console.error(e);return bad(e?.message||'Server error',500)}}};
